CREATE DATABASE IF NOT EXISTS padi_eform;
USE padi_eform;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  birthday DATE NOT NULL,
  language VARCHAR(20) NOT NULL
);
